spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "690815069450-0gsk4is3duuc8ido2vaqb1mb400k4v0r.apps.googleusercontent.com"
            client-secret: "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"
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile